# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_1_0/system_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_1_0 || ORIG_REF_NAME==system_xlconcat_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_1/system_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_1 || ORIG_REF_NAME==system_axi_smc_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_200M_1/system_rst_ps7_0_200M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_200M_1 || ORIG_REF_NAME==system_rst_ps7_0_200M_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_xbar_0/system_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==system_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_0/system_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_2/system_axi_mem_intercon_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_2 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_pc_0/system_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_1/system_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1 || ORIG_REF_NAME==system_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/system/ip/system_acc_top_0_0/system_acc_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_acc_top_0_0 || ORIG_REF_NAME==system_acc_top_0_0} -quiet] -quiet

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/system_ooc.xdc
