# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.srcs/sources_1/bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1.xci
# IP: The module: 'system_axi_mem_intercon_imp_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.srcs/sources_1/bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1.xci
# IP: The module: 'system_axi_mem_intercon_imp_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
