# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.srcs/sources_1/bd/system/ip/system_axi_smc_1/system_axi_smc_1.xci
# IP: The module: 'system_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/bd_8422.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_0/bd_8422_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/bd_8422_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_2/bd_8422_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_3/bd_8422_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_4/bd_8422_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_5/bd_8422_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_6/bd_8422_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_7/bd_8422_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_8/bd_8422_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_9/bd_8422_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_10/bd_8422_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_11/bd_8422_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_12/bd_8422_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/bd_8422_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/bd_8422_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_5/bd_8422_s00a2s_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_6/bd_8422_sarn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_7/bd_8422_srn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_8/bd_8422_sawn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_9/bd_8422_swn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_10/bd_8422_sbn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_11/bd_8422_m00s2a_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.srcs/sources_1/bd/system/ip/system_axi_smc_1/system_axi_smc_1.xci
# IP: The module: 'system_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/bd_8422.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_0/bd_8422_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/bd_8422_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_2/bd_8422_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_3/bd_8422_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_4/bd_8422_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_5/bd_8422_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_6/bd_8422_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_7/bd_8422_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_8/bd_8422_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_9/bd_8422_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_10/bd_8422_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_11/bd_8422_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_12/bd_8422_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/bd_8422_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_1/bd_8422_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_5/bd_8422_s00a2s_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_6/bd_8422_sarn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_7/bd_8422_srn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_8/bd_8422_sawn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_9/bd_8422_swn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_10/bd_8422_sbn_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/bd_0/ip/ip_11/bd_8422_m00s2a_0_ooc.xdc

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gorruy/Desktop/diploma--2-/vivado/zynq_test.gen/sources_1/bd/system/ip/system_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
